# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: 'buildPipeline'
      # project: 'dotnetapp'
      source: 'Build Pipeline'
      branch: 'main'
      trigger: true
stages:
  - stage: DevelopmentServer
    variables:
      IISWebsiteName: dotnetApp
    displayName: 'Development Server Deploy'
    pool:
      vmImage: windows-latest
    jobs:
      - template: temp/depTemp.yaml
        parameters:
          IISWebsiteName: dotnetApp
          depending: []
  - stage: stagingServer
    dependsOn: 'DevelopmentServer'
    displayName: 'Staging Server Deploy'
    variables:
      IISWebsiteName: stagingapp
    pool:
      vmImage: windows-latest
    jobs:
      - job: 'ManualApproval'
        timeoutInMinutes: 4320
        steps:
          - checkout: none
          # - task: ManualValidation@0
          #   timeoutInMinutes: 1440
          #   inputs:
          #     notifyUsers: 'akash.wave21@gmail.com'
          #     instructions: 'Check previous job and approve'
          #     onTimeout: 'resume'
      - template: temp/depTemp.yaml
        parameters:
          IISWebsiteName: stagingapp
          depending: ManualApproval
        