# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: 'buildPipeline'
      # project: 'dotnetapp'
      source: 'Build Pipeline'
      branch: 'main'
      trigger: true
stages:
  - stage: DevelopmentServer
    variables:
      IISWebsiteName: dotnetApp
    displayName: 'Development'
    pool:
      vmImage: windows-latest
    jobs:
      - template: temp/depTemp.yaml
        parameters:
          IISWebsiteName: dotnetApp
          envtype: dev.WIN-VM
  - stage: stagingServer
    dependsOn: 'DevelopmentServer'
    displayName: 'Staging'
    variables:
      IISWebsiteName: stagingapp
    pool:
      vmImage: windows-latest
    jobs:
      - template: temp/depTemp.yaml
        parameters:
          IISWebsiteName: stagingapp
          envtype: staging.WIN-VM
  - stage: productionServer
    dependsOn: 'stagingServer'
    displayName: 'Production'
    pool:
      vmImage: windows-latest
    jobs:
      - template: temp/depTemp.yaml
        parameters:
          IISWebsiteName: prodsite
          envtype: production.WIN-VM
        