parameters:
  IISWebsiteName: dotnetApp
jobs:
  - deployment: Deployapp
    displayName: 'Deploy Dotnet App'
    environment: 'dev.WIN-VM'
    timeoutInMinutes: 4320
    strategy:
      runOnce:
        deploy:
          steps:
            - task: ManualValidation@0
              displayName: 'Approval'
              timeoutInMinutes: 1440
              inputs:
                notifyUsers: 'akash.wave21@gmail.com'
                instructions: 'Check previous job.'
                onTimeout: 'resume'
            - checkout: none

            - download: 'buildPipeline'
              name: 'DownloadArtifact'
              displayName: 'Download Artifact'
              artifact: 'drop'
            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: 'C:\azagent\A1\_work\1\buildPipeline\drop\*.zip'
                destinationFolder: '$(pipeline.workspace)\a'
                cleanDestinationFolder: true
                overwriteExistingFiles: false
            - task: IISWebAppManagementOnMachineGroup@0
              name: 'StopService'
              displayName: 'Stop Service'
              inputs:
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'StopWebsite'
                StartStopWebsiteName: '${{ parameters.IISWebsiteName }}'
            - task: IISWebAppDeploymentOnMachineGroup@0
              name: 'DeployApp'
              displayName: 'Deploy Application'
              inputs:
                WebSiteName: '${{ parameters.IISWebsiteName }}'
                Package: '$(pipeline.workspace)\a'
                TakeAppOfflineFlag: true
            - task: IISWebAppDeploymentOnMachineGroup@0
              name: 'DeployAppRetry'
              condition: failed()
              displayName: 'Deploy Application Retry If Failed'
              inputs:
                WebSiteName: '${{ parameters.IISWebsiteName }}'
                Package: '$(pipeline.workspace)\a'
                TakeAppOfflineFlag: true
            - task: IISWebAppManagementOnMachineGroup@0
              name: 'StartService'
              displayName: 'Start Service'
              inputs:
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'StartWebsite'
                StartStopWebsiteName: '${{ parameters.IISWebsiteName }}'
